### ISSUE TITLE
<span>

### ISSUE THREAD

**Issue by gdedi001** [drodrigueztx/prj-rev-bwfs-dasmoto#2]
Great job implementing the `<span>` tags with appropriate classes to achieve the blue font color!
https://github.com/drodrigueztx/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/index.html#L13-L15

**Comment by drodrigueztx** [comment]
Thanks! I actually used the inspect element tool on Chrome to give me a better idea of what direction to go for this.
